modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory

license="MIT"

[[mods]] #mandatory

modId="tpsound" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Ender Pearl teleport sound" #mandatory

logoFile="icon.png" #optional

authors="Nero" #optional

description='''
Mod adds a teleportation sound when using Ender pearls, as in minecraft bedrock edition.
'''

[[dependencies.tpsound]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[47,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.tpsound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
